apiVersion: 1

datasources:
  - name: Prometheus
    uid: snabju-prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: PostgreSQL
    uid: snabju-postgres
    type: postgres
    url: ${PG_HOST}:5432
    database: ${PG_DBNAME}
    user: ${PG_USER}
    secureJsonData:
      password: ${PG_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    editable: false