'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';

function keyBytes(key: string) { const padded = (key + '='.repeat((4 - key.length % 4) % 4)).replace(/-/g, '+').replace(/_/g, '/'); const raw = atob(padded); return Uint8Array.from(raw, c => c.charCodeAt(0)); }

export default function SettingsPage() {
  const [percent, setPercent] = useState(''); const [message, setMessage] = useState(''); const [pushBusy, setPushBusy] = useState(false);
  useEffect(() => { api.adminGetB2BDiscount().then(x => setPercent(String(x))).catch(() => setMessage('Ошибка загрузки')); }, []);
  const save = async () => { const value = Number(percent); if (!Number.isFinite(value) || value < 0 || value >= 100) return setMessage('Введите число от 0 до 99.99'); try { setPercent(String(await api.adminUpdateB2BDiscount(value))); setMessage('Сохранено'); } catch (e: any) { setMessage(e.message); } };
  const enablePush = async () => { const key = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; if (!key || !('serviceWorker' in navigator) || !('PushManager' in window)) return setMessage('Установите сайт на экран «Домой» и откройте его оттуда.'); setPushBusy(true); try { const registration = await navigator.serviceWorker.register('/sw.js'); const permission = await Notification.requestPermission(); if (permission !== 'granted') throw new Error('Разрешение на уведомления не выдано'); const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: keyBytes(key) }); await api.subscribePush(subscription); setMessage('Push-уведомления включены'); } catch (e: any) { setMessage(e.message ?? 'Не удалось включить уведомления'); } finally { setPushBusy(false); } };
  return <div className="max-w-xl"><h1 className="text-2xl font-extrabold text-ink">Оптовые условия</h1><p className="text-sm text-muted">Единая скидка действует на все товары и коробки.</p><div className="mt-4 bg-white border border-divider rounded-xl p-4"><label className="block text-xs text-muted mb-2">Скидка для юрлиц, %</label><input className="w-full text-xl font-bold outline-none" type="number" min="0" max="99.99" step="0.01" value={percent} onChange={e => setPercent(e.target.value)}/><button className="mt-4 px-5 py-3 rounded-xl text-white bg-ink font-bold" onClick={save}>Сохранить</button></div><div className="mt-4 bg-white border border-divider rounded-xl p-4"><h2 className="text-base font-bold text-ink m-0">Уведомления о заказах</h2><p className="text-sm text-muted">Установите Snabju на экран «Домой» и включите системные уведомления.</p><button disabled={pushBusy} className="px-5 py-3 rounded-xl text-white bg-ink font-bold disabled:opacity-60" onClick={enablePush}>{pushBusy ? 'Включаем…' : 'Включить уведомления'}</button></div>{message && <p className="mt-3 text-sm text-muted">{message}</p>}</div>;
}
