import { StoreData } from './types';

export const SNABJU_DATA: StoreData = {
  brand: {
    name: 'snabju',
    tagline: 'Утеплители · пены · герметики',
    address: 'Склад: Котельники, МКАД 22-й км',
    phone: '+7 800 555-12-04',
  },

  categories: [
    { id: 'mineral',  title: 'Минеральная вата',        count: 84,  swatch: '#d8c9a8', icon: 'wool' },
    { id: 'foam',     title: 'Пенопласт и ППС',         count: 56,  swatch: '#f1ece1', icon: 'block' },
    { id: 'xps',      title: 'Экструдированный ППС',    count: 42,  swatch: '#cf8f5e', icon: 'xps' },
    { id: 'pur',      title: 'Монтажная пена',          count: 38,  swatch: '#ffd17a', icon: 'can' },
    { id: 'sealants', title: 'Герметики',               count: 71,  swatch: '#c4d8d2', icon: 'tube' },
    { id: 'tape',     title: 'Ленты и плёнки',          count: 49,  swatch: '#e8dcc4', icon: 'roll' },
    { id: 'membrane', title: 'Гидро-пароизоляция',      count: 33,  swatch: '#a8b0a4', icon: 'sheet' },
    { id: 'tools',    title: 'Расходники и инструмент', count: 27,  swatch: '#2a2620', icon: 'tool' },
  ],

  products: [
    {
      id: 'rw-light-50',
      sku: 'RW-LB-50-100',
      title: 'Минвата Rockwool Лайт Баттс',
      sub: 'Плита 1000×600×50, 8 шт. — 4.8 м²',
      cat: 'mineral', catLabel: 'Минвата',
      unit: 'упак.', unitDetail: '4.8 м² / упак.',
      price: 1290, oldPrice: 1480,
      pricePallet: 38000, palletQty: 32,
      stock: 412, stockUnit: 'упак.',
      eta: 'завтра до 14:00',
      rating: 4.8, reviews: 326,
      tag: 'Хит',
      specs: [
        ['Плотность',    '37 кг/м³'],
        ['Теплопровод.', '0.036 Вт/м·К'],
        ['Горючесть',    'НГ'],
        ['Толщина',      '50 мм'],
      ],
    },
    {
      id: 'tn-blok-100',
      sku: 'TN-BL-100-50',
      title: 'ТехноНИКОЛЬ Блок 100',
      sub: 'Плита 1200×600×100, 4 шт. — 2.88 м²',
      cat: 'mineral', catLabel: 'Минвата',
      unit: 'упак.', unitDetail: '2.88 м² / упак.',
      price: 1640, oldPrice: null,
      pricePallet: 49500, palletQty: 30,
      stock: 218, stockUnit: 'упак.',
      eta: 'завтра до 18:00',
      rating: 4.7, reviews: 184,
      tag: null,
      specs: [
        ['Плотность',    '45 кг/м³'],
        ['Теплопровод.', '0.038 Вт/м·К'],
        ['Горючесть',    'НГ'],
        ['Толщина',      '100 мм'],
      ],
    },
    {
      id: 'pena-titan-65',
      sku: 'TT-O2-65',
      title: 'Пена монтажная Titan O2 65л',
      sub: 'Профессиональная, всесезонная',
      cat: 'pur', catLabel: 'Монтажная пена',
      unit: 'баллон', unitDetail: '850 мл',
      price: 480, oldPrice: 540,
      pricePallet: 27800, palletQty: 60,
      stock: 1248, stockUnit: 'баллон',
      eta: 'сегодня до 21:00',
      rating: 4.9, reviews: 512,
      tag: '−12%',
      specs: [
        ['Выход',        '65 л'],
        ['Расширение',   'до 30%'],
        ['Темп. работы', '−10…+35 °C'],
        ['Время резки',  '40 мин'],
      ],
    },
    {
      id: 'xps-tn-30',
      sku: 'XPS-TN-30-50',
      title: 'XPS ТехноНИКОЛЬ Carbon 30',
      sub: 'Плита 1180×580×50, 8 шт. — 5.47 м²',
      cat: 'xps', catLabel: 'Экстр. ППС',
      unit: 'упак.', unitDetail: '5.47 м² / упак.',
      price: 2180, oldPrice: null,
      pricePallet: 65400, palletQty: 30,
      stock: 96, stockUnit: 'упак.',
      eta: 'послезавтра',
      rating: 4.8, reviews: 241,
      tag: null,
      specs: [
        ['Плотность',    '30 кг/м³'],
        ['Теплопровод.', '0.029 Вт/м·К'],
        ['Прочность',    '250 кПа'],
        ['Толщина',      '50 мм'],
      ],
    },
    {
      id: 'silikon-ck',
      sku: 'CK-SAN-280',
      title: 'Силикон санитарный Ceresit CS 25',
      sub: 'Картридж 280 мл, белый',
      cat: 'sealants', catLabel: 'Герметики',
      unit: 'картридж', unitDetail: '280 мл',
      price: 320, oldPrice: null,
      pricePallet: 5400, palletQty: 20,
      stock: 786, stockUnit: 'шт.',
      eta: 'сегодня до 21:00',
      rating: 4.6, reviews: 98,
      tag: null,
      specs: [
        ['Объём',        '280 мл'],
        ['Цвет',         'белый'],
        ['Применение',   'санузлы'],
        ['Темп. экспл.', '−40…+150'],
      ],
    },
    {
      id: 'isover-profi',
      sku: 'ISO-PROFI-50',
      title: 'ISOVER Профи',
      sub: 'Мат 5000×1220×50 — 6.1 м²',
      cat: 'mineral', catLabel: 'Минвата',
      unit: 'рулон', unitDetail: '6.1 м² / рулон',
      price: 1490, oldPrice: 1690,
      pricePallet: 41200, palletQty: 28,
      stock: 156, stockUnit: 'рулон',
      eta: 'завтра до 14:00',
      rating: 4.7, reviews: 211,
      tag: 'Акция',
      specs: [
        ['Плотность',    '11 кг/м³'],
        ['Теплопровод.', '0.040 Вт/м·К'],
        ['Горючесть',    'НГ'],
        ['Толщина',      '50 мм'],
      ],
    },
  ],

  promos: [
    { id: 'p1', title: 'Минвата Rockwool',   sub: 'до −15% при заказе паллеты', accent: true },
    { id: 'p2', title: 'Бесплатная доставка', sub: 'от 25 000 ₽ по Москве',     accent: false },
    { id: 'p3', title: 'Корпоративный счёт',  sub: 'отсрочка платежа 14 дней',  accent: false },
  ],

  orders: [
    { id: 'SN-24811', date: '06 мая',    status: 'В пути',    statusKind: 'progress', items: 4, total: 18420, eta: 'сегодня 14:00–18:00' },
    { id: 'SN-24796', date: '04 мая',    status: 'Доставлен', statusKind: 'done',     items: 7, total: 42180, eta: null },
    { id: 'SN-24744', date: '28 апреля', status: 'Доставлен', statusKind: 'done',     items: 2, total: 3640,  eta: null },
  ],

  cart: [
    { id: 'rw-light-50',   qty: 12, asPallet: false },
    { id: 'pena-titan-65', qty:  6, asPallet: false },
    { id: 'silikon-ck',    qty:  4, asPallet: false },
  ],

  filters: {
    thickness: ['30', '50', '80', '100', '150', '200'],
    density:   ['11–15', '30–45', '45–80', '80–125', '125+'],
    brands:    ['Rockwool', 'ТехноНИКОЛЬ', 'ISOVER', 'PAROC', 'Knauf', 'URSA'],
    flammable: ['НГ', 'Г1', 'Г2'],
  },
};
